enum OMNIX_MODULE {
  OOM = "OOM",
  OIM = "OIM",
  OLM = "OLM",
  OSRM = "OSRM",
  OMA = "OMA",
  OSM = "OSM",
  OITM = "OITM",
  LISTENER = "LISTENER",
  DOWNLOAD = "DOWNLOAD",
  PRIORITIZATION = "PRIORITIZATION"
}

export default OMNIX_MODULE